<template>
  <div>
    <CCard class="mb-4">
      <CCardBody>
        <CListGroup>
          <CListGroupItem>
            <a
              href="https://raw.githubusercontent.com/mhqb365/webdicebot-awesome-scripts/master/allTatic.lua"
              target="_blank"
            >
              allTatic.lua
            </a>
          </CListGroupItem>
          <CListGroupItem>
            <a
              href="https://raw.githubusercontent.com/mhqb365/webdicebot-awesome-scripts/master/bet-boom.lua"
              target="_blank"
            >
              bet-boom.lua
            </a>
          </CListGroupItem>
          <CListGroupItem>
            <a
              href="https://raw.githubusercontent.com/mhqb365/webdicebot-awesome-scripts/master/clean.lua"
              target="_blank"
            >
              clean.lua
            </a>
          </CListGroupItem>
          <CListGroupItem>
            <a
              href="https://raw.githubusercontent.com/mhqb365/webdicebot-awesome-scripts/master/forDuck.lua"
              target="_blank"
            >
              forDuck.lua
            </a>
          </CListGroupItem>
          <CListGroupItem>
            <a
              href="https://raw.githubusercontent.com/mhqb365/webdicebot-awesome-scripts/master/makecolor.lua"
              target="_blank"
            >
              makecolor.lua
            </a>
          </CListGroupItem>
          <CListGroupItem>
            <a
              href="https://raw.githubusercontent.com/mhqb365/webdicebot-awesome-scripts/master/new-style.lua"
              target="_blank"
            >
              new-style.lua
            </a>
          </CListGroupItem>
          <CListGroupItem>
            <a
              href="https://raw.githubusercontent.com/mhqb365/webdicebot-awesome-scripts/master/newAI.lua"
              target="_blank"
            >
              newAI.lua
            </a>
          </CListGroupItem>
          <CListGroupItem>
            <a
              href="https://raw.githubusercontent.com/mhqb365/webdicebot-awesome-scripts/master/newStardy.lua"
              target="_blank"
            >
              newStardy.lua
            </a>
          </CListGroupItem>
          <CListGroupItem>
            <a
              href="https://raw.githubusercontent.com/mhqb365/webdicebot-awesome-scripts/master/newVersion.lua"
              target="_blank"
            >
              newVersion.lua
            </a>
          </CListGroupItem>
          <CListGroupItem>
            <a
              href="https://raw.githubusercontent.com/mhqb365/webdicebot-awesome-scripts/master/noCacularBet.lua"
              target="_blank"
            >
              noCacularBet.lua
            </a>
          </CListGroupItem>
          <CListGroupItem>
            <a
              href="https://raw.githubusercontent.com/mhqb365/webdicebot-awesome-scripts/master/risk.lua"
              target="_blank"
            >
              risk.lua
            </a>
          </CListGroupItem>
          <CListGroupItem>
            <a
              href="https://raw.githubusercontent.com/mhqb365/webdicebot-awesome-scripts/master/smartBet.lua"
              target="_blank"
            >
              smartBet.lua
            </a>
          </CListGroupItem>
          <CListGroupItem>
            <a
              href="https://raw.githubusercontent.com/mhqb365/webdicebot-awesome-scripts/master/taticNew.lua"
              target="_blank"
            >
              taticNew.lua
            </a>
          </CListGroupItem>
        </CListGroup>
      </CCardBody>
    </CCard>
  </div>
</template>

<script>
export default {}
</script>

<style></style>
