export default [
  {
    component: 'CNavTitle',
    name: 'Dashboard',
    permission: 0,
  },
  {
    component: 'CNavItem',
    name: 'Web DiceBot',
    to: '/pages/home',
    icon: 'cil-home',
    permission: 0,
  },
  {
    component: 'CNavItem',
    name: 'Get Started',
    to: '/get-started',
    icon: 'cil-book',
    permission: 0,
  },
  {
    component: 'CNavItem',
    name: 'Bot Installer',
    to: '/bot-installer',
    icon: 'cil-3d',
    permission: 0,
  },
  {
    component: 'CNavItem',
    name: 'Buy License',
    to: '/buy-license',
    icon: 'cil-cart',
    permission: 0,
  },
  {
    component: 'CNavItem',
    name: 'My License',
    to: '/my-license',
    icon: 'cil-star',
    permission: 0,
  },
  {
    component: 'CNavItem',
    name: 'My Wallet',
    to: '/my-wallet',
    icon: 'cil-wallet',
    permission: 0,
  },
  {
    component: 'CNavItem',
    name: 'Profile',
    to: '/profile',
    icon: 'cil-user',
    permission: 0,
  },
  {
    component: 'CNavItem',
    name: 'Logout',
    to: '/pages/logout',
    icon: 'cil-account-logout',
    permission: 0,
  },
  {
    component: 'CNavTitle',
    name: 'Admin',
    permission: 2,
  },
  {
    component: 'CNavItem',
    name: 'User Manager',
    to: '/user-manager',
    icon: 'cil-user',
    permission: 2,
  },
  {
    component: 'CNavItem',
    name: 'License Manager',
    to: '/license-manager',
    icon: 'cil-star',
    permission: 2,
  },
  {
    component: 'CNavItem',
    name: 'Send Notify',
    to: '/send-notify',
    icon: 'cib-telegram-plane',
    permission: 2,
  },
]
